In [6]:
import rasterio

In [12]:
ds_path = '../data/raster_to_update.tif'
ds = rasterio.open(ds_path)
arr = ds.read(1)
ds.shape, ds.dtypes

((1439, 1560), ('uint8',))

In [13]:
import numpy as np
np.unique(arr, return_counts=True)

(array([0, 1, 2, 3, 4], dtype=uint8),
 array([1780986,  153547,  196223,   86853,   27231]))

In [15]:
arr[arr==1] = 201
arr[arr==2] = 202
arr[arr==201] = 2
arr[arr==202] = 1

In [16]:
np.unique(arr, return_counts=True)

(array([0, 1, 2, 3, 4], dtype=uint8),
 array([1780986,  196223,  153547,   86853,   27231]))

In [26]:
out_path = '/tmp/out.tiff'
with rasterio.open(
        out_path,
        'w',
        driver='GTiff',
        height=arr.shape[0],
        width=arr.shape[1],
        count=1,
        dtype=rasterio.uint8,
        crs=rasterio.crs.CRS.from_epsg(4326),
        transform=ds.transform,
    ) as dst:
    dst.write(arr, 1)
dst.close()

In [27]:
ds = rasterio.open(out_path)
arr = ds.read(1)
ds.shape, ds.dtypes
np.unique(arr, return_counts=True)

(array([0, 1, 2, 3, 4], dtype=uint8),
 array([1780986,  196223,  153547,   86853,   27231]))